os:
  - linux
  - osx
language: java
addons:
  homebrew:
    update: true
    packages:
      - ant@1.9
jobs:
  include:
    - stage: test
      script: mvn clean install && sh deploy.sh
    -  
      script: mvn clean install -U  && sh deploy.sh
